LoveBundle_ultrahome:
    path:      /
    defaults:
        _controller: EJLoveBundle:Game:toindex

LoveBundle_home:
    path:      /home
    defaults:
        _controller: EJLoveBundle:Game:index

LoveBundle_admin:
    path:      /admin
    defaults:
        _controller: EJLoveBundle:Party:admin

LoveBundle_init:
    path:      /admin/init
    defaults:
        _controller: EJLoveBundle:Game:init

LoveBundle_create:
    path:      /game/createGame/{gameid}
    defaults:
        _controller: EJLoveBundle:Game:create
    requirements:
            gameid: \d+
            
LoveBundle_reset:
    path:      /game/reset/{gameid}
    defaults:
        _controller: EJLoveBundle:Game:reset
    requirements:
            gameid: \d+

LoveBundle_view:
    path:      /game/{gameid}
    defaults:
        _controller: EJLoveBundle:Game:view
    requirements:
        gameid: \d+

LoveBundle_playcard:
    path:      /game/{gameid}/playcard/{playerid}/{cardid}
    defaults:
        _controller: EJLoveBundle:Game:playcard
    requirements:
        gameid: \d+
        playerid: "[a-zA-Z0-9-]+"
        cardid: \d+

LoveBundle_refresh:
    path:      /game/{gameid}/refresh
    defaults:
        _controller: EJLoveBundle:Game:getTour
    requirements:
        gameid: \d+
        
LoveBundle_ListParty:
    path:      /party/list
    defaults:
        _controller: EJLoveBundle:Party:list

LoveBundle_createParty:
    path:      /party/createParty
    defaults:
        _controller: EJLoveBundle:Party:createParty
        
LoveBundle_viewParty:
    path:      /party/viewParty/{partyid}
    defaults:
        _controller: EJLoveBundle:Party:viewParty
        

LoveBundle_partyrefresh:
    path:      /party/refresh/{partyid}
    defaults:
        _controller: EJLoveBundle:Party:getNbJoueurs
    requirements:
        gameid: \d+

LoveBundle_joinParty:
    path:      /party/joinParty/{partyid}
    defaults:
        _controller: EJLoveBundle:Party:joinParty

