LoveBundle_ultrahome:
    path:      /
    defaults:
        _controller: EJLoveBundle:Game:toindex

LoveBundle_home:
    path:      /home
    defaults:
        _controller: EJLoveBundle:Game:index

LoveBundle_view:
    path:      /game/{gameid}
    defaults:
        _controller: EJLoveBundle:Game:view
    requirements:
        gameid: \d+