# src/ProjetWeb/TestBundle/Resources/config/routing.yml

TestBundle_home:
    path:      /{page}
    defaults:
        _controller: ProjetWebTestBundle:Advert:index
        page:      1
    requirements:
        page: \d*

TestBundle_view:
    path:      /advert/{id}
    defaults:
        _controller: ProjetWebTestBundle:Advert:view
    requirements:
        id: \d+

TestBundle_add:
    path:      /add
    defaults:
        _controller: ProjetWebTestBundle:Advert:add

TestBundle_edit:
    path:      /edit/{id}
    defaults:
        _controller: ProjetWebTestBundle:Advert:edit
    requirements:
        id: \d+

TestBundle_delete:
    path:      /delete/{id}
    defaults:
        _controller: ProjetWebTestBundle:Advert:delete
    requirements:
        id: \d+